/**
 * COWBNB Data Models for Etapa A
 * Firestore Collections Schema Definitions
 * 
 * Principles:
 * - Minimal required fields for Etapa A MVP
 * - Backend controls state transitions and critical fields
 * - All timestamps in milliseconds (UTC)
 * - IDs: Auto-generated for documents, auth.uid for users
 * - Role/status values immutable on validation layer
 */

// ============================================================================
// 1. USERS COLLECTION
// ============================================================================

export type UserRole = 'owner' | 'renter';
export type UserStatus = 'active' | 'suspended' | 'deleted';

/**
 * Document ID: auto-generated (NOT uid, separate from Firebase Auth)
 * Alternative: Use uid directly as document ID for simplicity in Etapa A
 * 
 * Decision for Etapa A: USE firebase auth.uid as document ID
 * Rationale: Simplifies security rules, reduces JOIN operations
 */
export interface User {
  // Identity & Structure
  uid: string; // Firebase Auth UID (also document ID in Etapa A)
  createdAt: number; // Timestamp in ms when user registered
  updatedAt: number; // Timestamp in ms of last profile update
  deletedAt?: number; // Soft delete timestamp

  // Profile Information
  email: string; // Unique, indexed
  fullName: string;
  phone: string; // E.164 format: +56912345678
  phonePrefix: string; // Country code: +56, +1, etc.
  
  // Role & Status (Backend-controlled)
  role: UserRole; // 'owner' or 'renter', set at registration
  status: UserStatus; // 'active' (default), 'suspended', 'deleted'
  
  // Optional: profile enrichment
  profileImageUrl?: string; // URL to Storage
  bio?: string; // Max 500 chars
  
  // Financial & Verification
  verificationStatus?: 'unverified' | 'pending' | 'verified'; // For future KYC
  paymentMethodId?: string; // Reference to customer payment method (Bold)
  
  // Preferences
  languagePreference?: 'es' | 'en'; // Default: 'es'
  emailNotifications?: boolean; // Default: true
  pushNotifications?: boolean; // Default: true
}

/**
 * Validation Rules for User:
 * - email: valid email format, unique across collection
 * - fullName: 2-100 chars, no special characters except spaces/hyphens
 * - phone: valid phone format, 7-15 digits
 * - role: only 'owner' or 'renter'
 * - status: only 'active', 'suspended', 'deleted'
 * - createdAt: must be <= current timestamp
 */

// ============================================================================
// 2. TERRENOS COLLECTION
// ============================================================================

export type TerrenoStatus = 'disponible' | 'reservado' | 'en_espera' | 'inactivo';

/**
 * Document ID: auto-generated by Firestore
 * Parent: root collection (not subcollection of users)
 * Rationale: Enables efficient filtering by status, price, location independent of owner
 */
export interface Terreno {
  // Identity & Ownership
  id: string; // Document ID (auto-generated)
  ownerId: string; // Reference to User.uid (indexed)
  createdAt: number; // Timestamp in ms
  updatedAt: number; // Last modification timestamp
  
  // Basic Information
  title: string; // Max 100 chars, searchable
  description: string; // Max 2000 chars
  
  // Physical Properties
  sizeHectares: number; // Must be > 0
  location: GeoLocation; // Lat/lng + geohash
  address?: string; // Human-readable address
  zone?: string; // Region/zone identifier for filtering
  
  // Financial
  priceMonthly: number; // Must be > 0, in CLP
  paymentTerms?: 'monthly' | 'quarterly' | 'annual'; // Default: 'monthly'
  
  // Features (amenities)
  features: string[]; // Array of feature IDs: ['irrigation', 'power', 'roads', 'certification']
  
  // Media
  images: TerrenoImage[]; // Array of image metadata
  coverImageUrl?: string; // URL of primary image
  
  // Status (Backend-controlled state machine)
  status: TerrenoStatus; // Default: 'disponible'
  
  // Metadata
  ratingAvg?: number; // Average review score 0-5, null if no reviews
  ratingCount?: number; // Count of reviews, default 0
  
  // Satellite Monitoring (initialized on creation)
  lastNdviCheck?: number; // Timestamp of last NDVI evaluation
  ndviStatus?: 'green' | 'yellow' | 'red'; // Risk level: green=ok, yellow=warning, red=action_needed
  ndviValue?: number; // Last NDVI index value (0-1 scale)
  
  // Legacy UI Mapping (internal, for transition)
  legacyStatus?: 'Activo' | 'Confirmado' | 'Pendiente'; // Maps to status field
}

export interface GeoLocation {
  latitude: number; // -90 to 90
  longitude: number; // -180 to 180
  geohash: string; // Precision level 6 recommended for ~1.2km accuracy
}

export interface TerrenoImage {
  id: string; // Unique identifier for image in this terreno
  url: string; // Storage URL
  thumbnailUrl?: string; // Compressed thumbnail URL
  uploadedAt: number; // Timestamp in ms
  uploadedBy: string; // Reference to User.uid (should match ownerId in Etapa A)
  order: number; // Display order in gallery
}

/**
 * Validation Rules for Terreno:
 * - sizeHectares: must be > 0 and <= 100000
 * - priceMonthly: must be > 0 and <= 10,000,000 CLP
 * - location: valid lat/lng coordinates
 * - geohash: precision 6-8
 * - images: max 10 images, each <= 5MB
 * - title/description: non-empty UTF-8 strings
 * - features: array of known feature IDs
 * - status: state transitions validated by Functions (see Etapa B)
 * 
 * Business Rules:
 * - Only owner (ownerId == auth.uid) can create/edit
 * - Status 'reservado' can only be set by backend (payment approval)
 * - Status 'en_espera' can only be set by backend (NDVI alert)
 * - Reactivation from 'en_espera' requires owner action via one-time token (Etapa E)
 */

// ============================================================================
// 3. RESERVAS COLLECTION
// ============================================================================

export type ReservaStatus = 'en_espera' | 'reservado' | 'activa' | 'finalizada' | 'cancelada';
export type PaymentStatus = 'pending' | 'approved' | 'failed' | 'refunded';

/**
 * Document ID: auto-generated by Firestore
 * Parent: root collection (not subcollection)
 * Rationale: Enables efficient querying by status, dateRange, participants
 */
export interface Reserva {
  // Identity & Participants
  id: string; // Document ID (auto-generated)
  terrenoId: string; // Reference to Terreno.id (indexed)
  renterId: string; // Reference to User.uid who is renting (indexed)
  ownerId: string; // Denormalized from Terreno for quick filtering (indexed)
  createdAt: number; // Timestamp in ms
  updatedAt: number; // Last modification timestamp
  
  // Booking Details
  startDate: number; // Timestamp in ms (start of lease)
  endDate: number; // Timestamp in ms (end of lease)
  durationDays: number; // Calculated as (endDate - startDate) / (24 * 60 * 60 * 1000)
  
  // Financial
  pricePerMonth: number; // Locked price at reservation time (from Terreno.priceMonthly)
  estimatedTotal: number; // Calculated: pricePerMonth * months, for reference
  currency: string; // Default: 'CLP'
  
  // Reservation Status (state machine, see Etapa C for transitions)
  status: ReservaStatus; // Default: 'en_espera'
  
  // Payment Status & Details
  paymentStatus: PaymentStatus; // Default: 'pending'
  paymentReference?: string; // External reference from Bold payment processor
  paymentMethod?: string; // 'credit_card', 'transfer', 'boleto', etc. (from Bold)
  
  // Expiration (Etapa C: auto-cancel if not paid)
  expiresAt?: number; // Timestamp when reservation expires if not paid
  expirationReason?: 'payment_timeout' | 'manual_cancellation' | 'owner_rejection';
  
  // Metadata
  notes?: string; // Internal notes (from renter or owner)
  rejectionReason?: string; // Why reservation was rejected (owner action)
  
  // Payment Events Audit Trail
  paymentEventId?: string; // Reference to payment_events collection
  lastPaymentAttempt?: number; // Timestamp of last payment attempt
  
  // Conversation Reference (Etapa D)
  conversationId?: string; // Reference to Conversacion document (created on approval)
}

/**
 * Validation Rules for Reserva:
 * - startDate: must be >= today (configurable buffer, e.g., 7 days ahead)
 * - endDate: must be > startDate (minimum 1 day, recommended 30 days)
 * - pricePerMonth: must match current Terreno.priceMonthly (for audit)
 * - status: only 'en_espera' on creation, transitions via backend
 * - expiresAt: should be startDate - 7 days (configurable)
 * - renterId != ownerId (cannot reserve own property)
 * - terrenoId must reference existing 'disponible' Terreno
 * 
 * State Machine (Etapa C):
 * en_espera -> reservado (payment approved)
 * en_espera -> cancelada (payment failed or timeout)
 * reservado -> activa (start date reached)
 * activa -> finalizada (end date reached or completed)
 * Any -> cancelada (owner rejection or error)
 */

// ============================================================================
// 4. PAYMENT_EVENTS COLLECTION (Etapa C)
// ============================================================================

export type PaymentEventType = 'checkout_initiated' | 'approved' | 'failed' | 'refunded' | 'webhook_received';

/**
 * Document ID: auto-generated by Firestore
 * Purpose: Audit trail of all payment events for troubleshooting and reconciliation
 * Immutable: never updated after creation
 */
export interface PaymentEvent {
  // Identity
  id: string; // Document ID (auto-generated)
  createdAt: number; // Timestamp in ms (when event occurred, not when recorded)
  recordedAt: number; // Timestamp in ms (when event was persisted)
  
  // References
  reservaId: string; // Reference to Reserva.id (indexed)
  terrenoId: string; // Denormalized from Reserva for filtering
  
  // Payment Processor Details
  externalReference: string; // Bold processor transaction ID (indexed for idempotence)
  eventType: PaymentEventType;
  
  // Amount & Status
  amount: number; // In cents for precision
  currency: string; // 'CLP'
  status: PaymentStatus;
  
  // Processing Details
  paymentMethod?: string; // 'credit_card', 'transfer', etc.
  errorCode?: string; // Bold error code if status='failed'
  errorMessage?: string; // Descriptive error message
  
  // Webhook (Etapa C)
  webhookSignature?: string; // For verification of Bold webhook payload
  isIdempotent?: boolean; // True if event is duplicate of prior externalReference
  
  // Metadata
  userAgent?: string; // Client context
  ipAddress?: string; // Anonymized if applicable
  notes?: string; // Internal notes
}

/**
 * Validation Rules:
 * - externalReference: unique across collection (idempotent key)
 * - amount: must match Reserva.estimatedTotal
 * - status: must be in PaymentStatus enum
 * - createdAt: must be <= recordedAt
 * - immutable after creation
 */

// ============================================================================
// 5. CONVERSACIONES COLLECTION (Messaging, Etapa D)
// ============================================================================

/**
 * Document ID: auto-generated by Firestore
 * Parent: root collection
 * Purpose: 1-to-1 conversation between owner and renter linked to a reservation
 * 
 * Strategy: Each Reserva creates ONE Conversacion when booking confirmed
 * Rationale: Messages must be contextualized to a specific land rental, not generic
 */
export interface Conversacion {
  // Identity
  id: string; // Document ID (auto-generated)
  createdAt: number; // Timestamp in ms
  updatedAt: number; // Last message timestamp
  
  // Participants (binary: owner + renter)
  ownerId: string; // Property owner (indexed)
  renterId: string; // Renter user (indexed)
  
  // Context
  reservaId: string; // Reference to Reserva.id (indexed, enables 1:1 mapping)
  terrenoId: string; // Denormalized from Reserva
  
  // Conversation Metadata
  lastMessageAt?: number; // Timestamp of most recent message (optional if no messages yet)
  lastMessageText?: string; // Preview of last message
  lastMessageSenderId?: string; // Who sent it (for UI: "You said..." vs "They said...")
  
  // Read Status (per participant)
  ownerLastReadAt?: number; // Timestamp owner marked as read
  renterLastReadAt?: number; // Timestamp renter marked as read
  
  // Counts
  messageCount?: number; // Total messages in conversation (for stats)
  unreadByOwner?: number; // Unread message count for owner
  unreadByRenter?: number; // Unread message count for renter
  
  // Status
  isActive?: boolean; // Default: true, set false if muted/archived
}

/**
 * Validation Rules:
 * - ownerId != renterId
 * - reservaId must reference existing, confirmed Reserva
 * - Only 1 Conversacion per (ownerId, renterId, terrenoId) tuple
 * - Read timestamps must be >= createdAt
 * - Read counts must be <= messageCount
 */

// ============================================================================
// 6. MENSAJES COLLECTION GROUP (Etapa D)
// ============================================================================

/**
 * Document ID: auto-generated by Firestore
 * Parent: Conversacion (subcollection: conversaciones/{id}/mensajes)
 * Also queryable as collection group: "mensajes"
 * 
 * Rationale for subcollection:
 * - Logical grouping: messages belong to conversation
 * - Enables pagination per conversation
 * - Supports collection group query for analytics (if needed)
 */
export interface Mensaje {
  // Identity
  id: string; // Document ID (auto-generated)
  conversationId: string; // Reference to parent Conversacion.id (for denormalization)
  createdAt: number; // Timestamp in ms (sent time, server-generated)
  
  // Content
  senderId: string; // Reference to User.uid (indexed for analytics)
  text: string; // Max 5000 characters
  
  // Metadata
  isEdited?: boolean; // False by default; if true, check editedAt
  editedAt?: number; // Timestamp if message was edited
  
  // Status (for future: read receipts, typing indicators)
  readAt?: number; // When recipient marked as read (optional in Etapa D)
  
  // Attachments (future, not in Etapa A)
  // attachmentUrls?: string[];
}

/**
 * Validation Rules:
 * - text: non-empty, max 5000 chars
 * - senderId: must be either Conversacion.ownerId or .renterId
 * - createdAt: server timestamp, immutable
 * - editedAt: if present, must be >= createdAt
 * - immutable except editedAt (in Etapa A: no editing)
 */

// ============================================================================
// 7. REVIEWS COLLECTION (Etapa F, basic structure included)
// ============================================================================

export interface Review {
  // Identity
  id: string; // Document ID (auto-generated)
  terrenoId: string; // Reference to Terreno.id (indexed)
  reservaId: string; // Reference to Reserva.id (indexed, ensures 1 review per reservation)
  reviewerId: string; // Reference to User.uid (renter leaving review) (indexed)
  revieweeId: string; // Reference to ownerId of Terreno (denormalized)
  createdAt: number; // Timestamp in ms
  updatedAt?: number; // If edited
  
  // Rating & Feedback
  rating: number; // 1-5 stars, integer
  title: string; // Short review title (max 100 chars)
  comment: string; // Review text (max 1000 chars)
  
  // Tags (helpful for filtering "great location", "responsive owner", etc.)
  tags?: string[]; // User-provided tags related to experience
  
  // Status
  isVisible?: boolean; // False if flagged/hidden (moderation in future)
  
  // Moderation (future)
  flaggedAt?: number; // Timestamp if flagged as inappropriate
  flagReason?: string; // Reason for flagging
}

/**
 * Validation Rules:
 * - rating: must be 1, 2, 3, 4, or 5
 * - title/comment: non-empty UTF-8
 * - reviewerId must not equal revieweeId
 * - reservaId must reference a 'finalizada' Reserva
 * - Only 1 review per reservaId (enforced via composite index + function logic)
 */

// ============================================================================
// 8. HELPER TYPES & ENUMS
// ============================================================================

export const TERRENO_FEATURES = {
  irrigation: { id: 'irrigation', label: 'Riego automático' },
  power: { id: 'power', label: 'Energía eléctrica' },
  roads: { id: 'roads', label: 'Caminos de acceso' },
  certification: { id: 'certification', label: 'Certificación ambiental' },
} as const;

export type TerrenoFeature = keyof typeof TERRENO_FEATURES;

export const TERRENO_STATUS_LABELS: Record<TerrenoStatus, string> = {
  disponible: 'Disponible',
  reservado: 'Reservado',
  en_espera: 'En espera',
  inactivo: 'Inactivo',
};

export const RESERVA_STATUS_LABELS: Record<ReservaStatus, string> = {
  en_espera: 'Esperando pago',
  reservado: 'Confirmada',
  activa: 'Activa',
  finalizada: 'Finalizada',
  cancelada: 'Cancelada',
};

// ============================================================================
// 9. COLLECTION PATHS & REFERENCES
// ============================================================================

export const FIRESTORE_PATHS = {
  users: 'users', // Documents: {uid}
  terrenos: 'terrenos', // Documents: {auto-id}
  reservas: 'reservas', // Documents: {auto-id}
  paymentEvents: 'payment_events', // Documents: {auto-id}
  conversaciones: 'conversaciones', // Documents: {auto-id}
  mensajes: 'mensajes', // Subcollection: conversaciones/{id}/mensajes
  reviews: 'reviews', // Documents: {auto-id}
  // Future Etapa E:
  ndviChecks: 'ndvi_checks',
  actionTokens: 'action_tokens',
  // Future Etapa F:
  recommendations: 'recommendations',
} as const;

export type CollectionPath = typeof FIRESTORE_PATHS[keyof typeof FIRESTORE_PATHS];
