/**
 * DATA VALIDATION & BUSINESS LOGIC RULES
 * Etapa A Model Validations
 * 
 * This document defines:
 * - Field-level type and constraint validations
 * - Business logic rules (cross-field dependencies)
 * - Role-based field access control
 * - State machine transitions (prepared for Etapa B+)
 */

// ============================================================================
// 1. USER VALIDATION RULES
// ============================================================================

export const USER_VALIDATION_RULES = {
  uid: {
    type: 'string',
    required: true,
    immutable: true,
    description: 'Firebase Auth UID, must match auth.uid at creation',
    pattern: /^[a-zA-Z0-9]{20,}$/, // Firebase UID format
    validation: `uid must match Firebase Auth UID`,
  },
  
  email: {
    type: 'string',
    required: true,
    immutable: false,
    unique: true, // Enforced at application level (query for duplicates before create)
    description: 'User email address',
    pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    minLength: 5,
    maxLength: 254,
    validation: `email must be valid email format, unique across users collection`,
  },
  
  fullName: {
    type: 'string',
    required: true,
    immutable: false,
    minLength: 2,
    maxLength: 100,
    pattern: /^[a-zA-Z\s\-áéíóúñÁÉÍÓÚÑ]+$/,
    validation: `fullName: 2-100 chars, letters/spaces/hyphens only, no numbers/special chars`,
  },
  
  phone: {
    type: 'string',
    required: true,
    immutable: false,
    minLength: 7,
    maxLength: 15,
    pattern: /^[0-9]{7,15}$/,
    validation: `phone: 7-15 digits, no formatting (digits only)`,
  },
  
  phonePrefix: {
    type: 'string',
    required: true,
    immutable: false,
    pattern: /^\+[0-9]{1,3}$/,
    description: 'Country code: +56 (Chile), +1 (USA), etc.',
    validation: `phonePrefix: +CC format where CC is 1-3 digit country code`,
  },
  
  role: {
    type: 'enum',
    required: true,
    immutable: true,
    enum: ['owner', 'renter'],
    description: 'User role set at registration, cannot change',
    validation: `role must be 'owner' or 'renter', immutable after creation`,
  },
  
  status: {
    type: 'enum',
    required: true,
    defaultValue: 'active',
    enum: ['active', 'suspended', 'deleted'],
    description: 'Account status, controlled by backend',
    validation: `status must be 'active', 'suspended', or 'deleted'`,
  },
  
  createdAt: {
    type: 'number',
    required: true,
    immutable: true,
    format: 'timestamp-ms',
    description: 'User creation timestamp',
    validation: `createdAt must be valid timestamp in milliseconds, <= current time`,
    serverGenerated: true,
  },
  
  updatedAt: {
    type: 'number',
    required: true,
    immutable: false,
    format: 'timestamp-ms',
    description: 'Last profile update timestamp',
    validation: `updatedAt must be >= createdAt`,
    serverGenerated: true,
  },
  
  profileImageUrl: {
    type: 'string',
    required: false,
    immutable: false,
    pattern: /^https:\/\/.*\.(jpeg|jpg|png|webp)$/,
    validation: `profileImageUrl must be HTTPS URL to image (if provided)`,
  },
  
  bio: {
    type: 'string',
    required: false,
    immutable: false,
    maxLength: 500,
    validation: `bio: optional, max 500 chars`,
  },
};

export const USER_BUSINESS_RULES = {
  rule_1: 'Owner user can create terrenos',
  rule_2: 'Renter user can create reservas',
  rule_3: 'Only backend can change user.status (role-based access)',
  rule_4: 'User email must be unique (check before insert)',
  rule_5: 'phone + phonePrefix must form valid E.164 number',
  rule_6: 'User cannot delete own account in Etapa A (business rule, future soft-delete only)',
};

// ============================================================================
// 2. TERRENO VALIDATION RULES
// ============================================================================

export const TERRENO_VALIDATION_RULES = {
  id: {
    type: 'string',
    required: true,
    immutable: true,
    description: 'Auto-generated document ID',
    validation: `id must be auto-generated by Firestore (non-editable)`,
  },
  
  ownerId: {
    type: 'reference',
    required: true,
    immutable: true,
    referenceTo: 'users/{uid}',
    validation: `ownerId must reference existing User document`,
  },
  
  title: {
    type: 'string',
    required: true,
    immutable: false,
    minLength: 5,
    maxLength: 100,
    validation: `title: 5-100 chars, may contain numbers/hyphens`,
  },
  
  description: {
    type: 'string',
    required: true,
    immutable: false,
    minLength: 20,
    maxLength: 2000,
    validation: `description: 20-2000 chars (detailed property info)`,
  },
  
  sizeHectares: {
    type: 'number',
    required: true,
    immutable: false,
    minValue: '> 0',
    maxValue: '100000',
    precision: 'up to 2 decimal places (e.g., 15.75)',
    validation: `sizeHectares must be in range (0, 100000]`,
  },
  
  location: {
    type: 'object',
    required: true,
    immutable: false,
    subfields: {
      latitude: {
        type: 'number',
        range: '[-90, 90]',
        precision: '6+ decimal places for ~10cm accuracy',
        validation: 'must be valid latitude',
      },
      longitude: {
        type: 'number',
        range: '[-180, 180]',
        precision: '6+ decimal places',
        validation: 'must be valid longitude',
      },
      geohash: {
        type: 'string',
        length: '6-8 chars (Geohash precision)',
        validation: 'geohash must be 6-8 char Geohash string',
        purpose: 'spatial indexing for map queries',
      },
    },
  },
  
  priceMonthly: {
    type: 'number',
    required: true,
    immutable: false,
    currency: 'CLP',
    minValue: '> 0',
    maxValue: '10000000',
    precision: 'integer (no cents for agricultural products)',
    validation: `priceMonthly must be in range (0, 10,000,000] CLP`,
  },
  
  features: {
    type: 'array<string>',
    required: true,
    immutable: false,
    validValues: ['irrigation', 'power', 'roads', 'certification'],
    minItems: 0,
    maxItems: 10,
    validation: `features array must contain only known feature IDs`,
  },
  
  images: {
    type: 'array<TerrenoImage>',
    required: true,
    immutable: false,
    minItems: 0,
    maxItems: 10,
    description: 'Gallery of property images',
    validation: `max 10 images, each <= 5MB, total doc size <= 1MB`,
  },
  
  status: {
    type: 'enum',
    required: true,
    defaultValue: 'disponible',
    enum: ['disponible', 'reservado', 'en_espera', 'inactivo'],
    validation: `status must be enum value, transitions controlled by backend`,
    backendControlled: true,
  },
  
  createdAt: {
    type: 'number',
    required: true,
    immutable: true,
    format: 'timestamp-ms',
    serverGenerated: true,
  },
  
  updatedAt: {
    type: 'number',
    required: true,
    immutable: false,
    format: 'timestamp-ms',
    serverGenerated: true,
  },
  
  ratingAvg: {
    type: 'number',
    required: false,
    immutable: false,
    range: '[0, 5]',
    precision: '0.01 (2 decimals)',
    validation: `ratingAvg must be average of all reviews (if reviews exist)`,
    backendControlled: true,
  },
  
  ratingCount: {
    type: 'number',
    required: false,
    immutable: false,
    minValue: 0,
    validation: `ratingCount must be >= 0, incremented by review triggers`,
    backendControlled: true,
  },
  
  lastNdviCheck: {
    type: 'number',
    required: false,
    immutable: false,
    format: 'timestamp-ms',
    validation: `lastNdviCheck timestamp of last satellite check (Etapa E)`,
    backendControlled: true,
  },
  
  ndviStatus: {
    type: 'enum',
    required: false,
    enum: ['green', 'yellow', 'red'],
    validation: `ndviStatus: health of pasture ('green'=ok, 'yellow'=warning, 'red'=action needed)`,
    backendControlled: true,
  },
};

export const TERRENO_BUSINESS_RULES = {
  rule_1: 'Only ownerId can create/edit terreno (security rule)',
  rule_2: 'New terreno defaults to status "disponible"',
  rule_3: 'Only backend can transition status to "reservado" (after payment approved)',
  rule_4: 'Only backend can transition status to "en_espera" (after NDVI alert)',
  rule_5: 'Cannot edit terreno if status != "disponible" (in Etapa A, relax in B)',
  rule_6: 'Price change does NOT affect active reservations (snapshot in Reserva)',
  rule_7: 'Deleting terreno: set status to "inactivo", keep data (soft delete)',
  rule_8: 'ratingAvg/ratingCount updated by Cloud Functions on review changes',
  rule_9: 'Images: enforce max size 5MB per file, max 10 files per terreno',
  rule_10: 'Geohash must be recalculated if lat/lng changes',
};

// ============================================================================
// 3. RESERVA VALIDATION RULES
// ============================================================================

export const RESERVA_VALIDATION_RULES = {
  id: {
    type: 'string',
    required: true,
    immutable: true,
    description: 'Auto-generated document ID',
  },
  
  terrenoId: {
    type: 'reference',
    required: true,
    immutable: true,
    referenceTo: 'terrenos/{id}',
    validation: `terrenoId must reference existing, "disponible" Terreno`,
  },
  
  renterId: {
    type: 'reference',
    required: true,
    immutable: true,
    referenceTo: 'users/{uid}',
    validation: `renterId must reference existing User with role='renter'`,
  },
  
  ownerId: {
    type: 'reference',
    required: true,
    immutable: true,
    referenceTo: 'users/{uid}',
    description: 'Denormalized from Terreno for quick filtering',
    validation: `ownerId must match Terreno.ownerId at creation time`,
  },
  
  startDate: {
    type: 'number',
    required: true,
    immutable: false,
    format: 'timestamp-ms',
    validation: `startDate must be >= (today + buffer days, e.g., 7 days)`,
  },
  
  endDate: {
    type: 'number',
    required: true,
    immutable: false,
    format: 'timestamp-ms',
    validation: `endDate must be > startDate (minimum 1 day, recommended 30+ days)`,
  },
  
  durationDays: {
    type: 'number',
    required: true,
    immutable: false,
    minValue: 1,
    maxValue: 9999,
    description: 'Calculated: (endDate - startDate) / 86400000',
    validation: `durationDays must be positive integer`,
    derived: true,
  },
  
  pricePerMonth: {
    type: 'number',
    required: true,
    immutable: true,
    currency: 'CLP',
    description: 'Snapshot of Terreno.priceMonthly at reservation time',
    validation: `pricePerMonth must match Terreno.priceMonthly at time of create`,
  },
  
  estimatedTotal: {
    type: 'number',
    required: true,
    immutable: false,
    currency: 'CLP',
    description: 'pricePerMonth * (durationDays / 30), for reference',
    validation: `estimatedTotal must be calculated consistently`,
    derived: true,
  },
  
  status: {
    type: 'enum',
    required: true,
    defaultValue: 'en_espera',
    enum: ['en_espera', 'reservado', 'activa', 'finalizada', 'cancelada'],
    validation: `status state machine transitions (see business rules)`,
    backendControlled: true,
  },
  
  paymentStatus: {
    type: 'enum',
    required: true,
    defaultValue: 'pending',
    enum: ['pending', 'approved', 'failed', 'refunded'],
    validation: `paymentStatus must be enum value`,
    backendControlled: true,
  },
  
  expiresAt: {
    type: 'number',
    required: false,
    immutable: false,
    format: 'timestamp-ms',
    description: 'Reservation auto-cancel if payment not received by this time',
    validation: `expiresAt should be startDate - 7 days (configurable buffer)`,
    backendControlled: true,
  },
  
  createdAt: {
    type: 'number',
    required: true,
    immutable: true,
    format: 'timestamp-ms',
    serverGenerated: true,
  },
  
  updatedAt: {
    type: 'number',
    required: true,
    immutable: false,
    format: 'timestamp-ms',
    serverGenerated: true,
  },
};

export const RESERVA_BUSINESS_RULES = {
  rule_1: 'renterId != ownerId (cannot reserve own property)',
  rule_2: 'terrenoId.status must be "disponible" at creation time',
  rule_3: 'New reserva defaults to status "en_espera", paymentStatus "pending"',
  rule_4: 'expiresAt should be set to startDate - 7 days (or configurable)',
  rule_5: 'Expired reserva auto-cancelled by scheduled job (Etapa B)',
  rule_6: 'pricePerMonth is immutable (snapshot) to preserve audit trail',
  rule_7: 'Only renterId can create reserva (security rule)',
  rule_8: 'Only backend can transition to "reservado" (payment prerequisite)',
  rule_9: 'No double-bookings: startDate/endDate vs existing reservas (check on create)',
  rule_10: 'Cancellation can be triggered by owner or system (payment timeout)',
  rule_11: 'conversationId created when status transitions to "reservado"',
};

// ============================================================================
// 4. CONVERSACION & MENSAJE VALIDATION RULES
// ============================================================================

export const CONVERSACION_VALIDATION_RULES = {
  id: {
    type: 'string',
    required: true,
    immutable: true,
  },
  
  ownerId: {
    type: 'reference',
    required: true,
    immutable: true,
    referenceTo: 'users/{uid}',
    validation: `ownerId must be property owner`,
  },
  
  renterId: {
    type: 'reference',
    required: true,
    immutable: true,
    referenceTo: 'users/{uid}',
    validation: `renterId must be renter from Reserva`,
  },
  
  reservaId: {
    type: 'reference',
    required: true,
    immutable: true,
    referenceTo: 'reservas/{id}',
    validation: `reservaId must reference confirmed Reserva`,
    uniqueConstraint: '1:1 mapping (only 1 Conversacion per Reserva)',
  },
  
  createdAt: {
    type: 'number',
    required: true,
    immutable: true,
    format: 'timestamp-ms',
    description: 'When conversation started (same as reserva confirmation)',
    serverGenerated: true,
  },
  
  updatedAt: {
    type: 'number',
    required: true,
    immutable: false,
    format: 'timestamp-ms',
    description: 'Last message sent',
  },
  
  lastMessageAt: {
    type: 'number',
    required: false,
    immutable: false,
    format: 'timestamp-ms',
    validation: `lastMessageAt must be timestamp of Mensaje.createdAt`,
  },
  
  lastMessageText: {
    type: 'string',
    required: false,
    immutable: false,
    maxLength: 250,
    description: 'Preview of last message (for inbox)',
  },
};

export const MENSAJE_VALIDATION_RULES = {
  id: {
    type: 'string',
    required: true,
    immutable: true,
    description: 'Auto-generated document ID',
  },
  
  senderId: {
    type: 'reference',
    required: true,
    immutable: true,
    referenceTo: 'users/{uid}',
    validation: `senderId must be either Conversacion.ownerId or .renterId`,
  },
  
  text: {
    type: 'string',
    required: true,
    immutable: true,
    minLength: 1,
    maxLength: 5000,
    validation: `text: non-empty, max 5000 chars`,
  },
  
  createdAt: {
    type: 'number',
    required: true,
    immutable: true,
    format: 'timestamp-ms',
    description: 'Server timestamp when message sent',
    serverGenerated: true,
  },
};

export const MESSAGING_BUSINESS_RULES = {
  rule_1: 'Conversacion created automatically when Reserva status -> "reservado"',
  rule_2: 'Only owner and renter can read/write messages in conversation',
  rule_3: 'Mensaje.senderId must match authenticated user (security rule)',
  rule_4: 'Messages are immutable (no editing in Etapa A)',
  rule_5: 'Message deletion not supported in Etapa A (soft-delete later)',
  rule_6: 'lastMessageAt/lastMessageText denormalized in Conversacion for perf',
  rule_7: 'Unread count computed on read (not stored), triggers notification',
};

// ============================================================================
// 5. PAYMENT_EVENT VALIDATION RULES
// ============================================================================

export const PAYMENT_EVENT_VALIDATION_RULES = {
  externalReference: {
    type: 'string',
    required: true,
    immutable: true,
    uniqueConstraint: 'must be unique (idempotent key for Bold webhook)',
    validation: `externalReference must match Bold transaction ID`,
  },
  
  status: {
    type: 'enum',
    required: true,
    enum: ['pending', 'approved', 'failed', 'refunded'],
    validation: `status transitions: pending -> approved/failed, approved -> refunded`,
  },
  
  amount: {
    type: 'number',
    required: true,
    immutable: true,
    currency: 'CLP',
    precision: 'integer (cents implicit)',
    validation: `amount must match Reserva.estimatedTotal * 100`,
  },
};

export const PAYMENT_EVENT_BUSINESS_RULES = {
  rule_1: 'PaymentEvent created by webhook handler (Bold API)',
  rule_2: 'externalReference checked for idempotence (duplicate webhook handling)',
  rule_3: 'approved event triggers Reserva status -> "reservado"',
  rule_4: 'failed event triggers Reserva status -> "cancelada"',
  rule_5: 'All PaymentEvents immutable (audit trail)',
  rule_6: 'Refund creates new PaymentEvent (does not modify original)',
};

// ============================================================================
// 6. REVIEW VALIDATION RULES
// ============================================================================

export const REVIEW_VALIDATION_RULES = {
  terrenoId: {
    type: 'reference',
    required: true,
    immutable: true,
    validation: `terrenoId must reference Terreno`,
  },
  
  reservaId: {
    type: 'reference',
    required: true,
    immutable: true,
    uniqueConstraint: 'only 1 review per Reserva',
    validation: `reservaId must reference finalized Reserva with status='finalizada'`,
  },
  
  rating: {
    type: 'number',
    required: true,
    immutable: false,
    enum: [1, 2, 3, 4, 5],
    validation: `rating must be integer 1-5`,
  },
  
  title: {
    type: 'string',
    required: true,
    immutable: false,
    maxLength: 100,
    validation: `title: max 100 chars`,
  },
  
  comment: {
    type: 'string',
    required: true,
    immutable: false,
    minLength: 10,
    maxLength: 1000,
    validation: `comment: 10-1000 chars`,
  },
};

export const REVIEW_BUSINESS_RULES = {
  rule_1: 'Only renter of finalized Reserva can create review',
  rule_2: 'Max 1 review per Reserva (enforced by composite index + function)',
  rule_3: 'Reviews trigger aggregation: Terreno.ratingAvg/ratingCount update',
  rule_4: 'Review creation triggers Cloud Function to update Terreno counters',
  rule_5: 'Review can be edited by reviewer within 30 days of creation (future)',
};

// ============================================================================
// 7. ROLE-BASED FIELD ACCESS (Etapa A MVP)
// ============================================================================

export const ROLE_BASED_ACCESS = {
  // USERS collection
  // Owner role can read: own document
  // Renter role can read: own document
  // Fields excluded from renter read: paymentMethodId, verificationStatus
  
  users: {
    owner: {
      canCreate: ['email', 'fullName', 'phone', 'phonePrefix'],
      canRead: ['email', 'fullName', 'phone', 'phonePrefix', 'role', 'status', 'bio', 'profileImageUrl'],
      canUpdate: ['fullName', 'phone', 'bio', 'profileImageUrl'],
      cannotUpdate: ['uid', 'email', 'role', 'phonePrefix', 'status', 'createdAt'],
    },
    renter: {
      canCreate: ['email', 'fullName', 'phone', 'phonePrefix'],
      canRead: ['email', 'fullName', 'phone', 'phonePrefix', 'role', 'status', 'bio', 'profileImageUrl'],
      canUpdate: ['fullName', 'phone', 'bio', 'profileImageUrl'],
      cannotUpdate: ['uid', 'email', 'role', 'phonePrefix', 'status', 'createdAt'],
    },
  },
  
  // TERRENOS collection
  terrenos: {
    owner: {
      canCreate: ['title', 'description', 'sizeHectares', 'location', 'priceMonthly', 'features', 'images'],
      canRead: 'all fields',
      canUpdate: ['title', 'description', 'sizeHectares', 'priceMonthly', 'features', 'images'],
      cannotUpdate: ['id', 'ownerId', 'status', 'ratingAvg', 'ratingCount', 'createdAt', 'ndviStatus'],
    },
    renter: {
      canRead: ['title', 'description', 'sizeHectares', 'location', 'priceMonthly', 'features', 'images', 'ratingAvg', 'ratingCount', 'ndviStatus'],
      canUpdate: [],
    },
    public: {
      canRead: 'title, description, location, priceMonthly, features, images, ratingAvg (if status="disponible")',
    },
  },
  
  // RESERVAS collection
  reservas: {
    renter: {
      canCreate: ['terrenoId', 'startDate', 'endDate'],
      canRead: 'own reservas only',
      canUpdate: [], // Cannot edit in Etapa A
    },
    owner: {
      canRead: 'terrenos they own (via terrenoId)',
      canUpdate: [], // Cannot edit in Etapa A
    },
  },
  
  // CONVERSACIONES & MENSAJES
  messaging: {
    participant: {
      canRead: 'conversations and messages where uid is participant',
      canCreate: 'messages in conversation (only)',
      canUpdate: [],
    },
    nonParticipant: {
      canRead: 'none',
      canCreate: 'none',
    },
  },
};

// ============================================================================
// 8. VALIDATION IMPLEMENTATION PSEUDO-CODE
// ============================================================================

export const VALIDATION_EXAMPLE = `
// Example: validateTerreno() function
export function validateTerreno(data: Partial<Terreno>, mode: 'create' | 'update'): ValidationResult {
  const errors: ValidationError[] = [];
  
  // Field-level validation
  if (mode === 'create') {
    if (!data.title || data.title.length < 5) errors.push(REQUIRED_FIELD('title'));
    if (!data.sizeHectares || data.sizeHectares <= 0) errors.push(RANGE_ERROR('sizeHectares', '> 0'));
    // ... more field validations
  }
  
  if (mode === 'update') {
    // Cannot update immutable fields
    if (data.id || data.ownerId) errors.push(IMMUTABLE_FIELD());
    // ... update validations
  }
  
  // Business logic validation
  if (data.startDate && data.endDate && data.startDate >= data.endDate) {
    errors.push(BUSINESS_RULE_ERROR('endDate must be > startDate'));
  }
  
  // Reference validation (async, in Cloud Function context)
  // if (data.terrenoId) {
  //   const terrenoDoc = await db.collection('terrenos').doc(data.terrenoId).get();
  //   if (!terrenoDoc.exists || terrenoDoc.data().status !== 'disponible') {
  //     errors.push(REFERENCE_ERROR('terrenoId must reference disponible Terreno'));
  //   }
  // }
  
  return {
    isValid: errors.length === 0,
    errors,
  };
}
`;
